// <auto-generated />
namespace SampleLogMaker.MyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addedthelogictosavevaluesinchildtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedthelogictosavevaluesinchildtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201311041659078_added the logic to save values in child table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
