// <auto-generated />
namespace SampleLogMaker.MyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changedaufitlogdatetimecolumntodatetimeoffset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedaufitlogdatetimecolumntodatetimeoffset));
        
        string IMigrationMetadata.Id
        {
            get { return "201311041432506_changed aufit log datetime column to datetime offset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
