// <auto-generated />
namespace SampleLogMaker.MyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class initial3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial3));
        
        string IMigrationMetadata.Id
        {
            get { return "201402081745041_initial3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
